services:
  wa_gate:
    image: kurniawan026/wa_gate:${APP_VERSION:-latest}
    container_name: wa_gate_app
    restart: always
    environment:
      - PHX_HOST=${PHX_HOST}
      - PHX_SCHEME=${PHX_SCHEME:-https}
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WAHA_API_URL=http://wa_engine:3000
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - APP_API_KEY=${APP_API_KEY}
      - POOL_SIZE=${POOL_SIZE:-10}
    ports:
      - "4000:4000"

  wa_engine:
    image: devlikeapro/waha
    container_name: wa_gate_engine
    restart: always
    environment:
      - WHATSAPP_API_KEY=${WAHA_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - waha_sessions:/app/.sessions

volumes:
  waha_sessions:
