services:
  wa_gate:
    image: kurniawan026/wa_gate:${APP_VERSION:-latest}
    container_name: wa_gate_app
    restart: always
    environment:
      - PHX_HOST=${PHX_HOST}
      - PHX_SCHEME=${PHX_SCHEME:-http}
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - EVOLUTION_API_URL=http://wa_engine:8080
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - APP_API_KEY=${APP_API_KEY}
      - POOL_SIZE=${POOL_SIZE:-10}
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wa_engine:
    image: evoapicloud/evolution-api:latest
    container_name: wa_gate_engine
    restart: always
    environment:
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - CACHE_REDIS_ENABLED=false
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://wa_gate:4000/api/webhooks/whatsapp
    ports:
      - "8081:8080"
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
